### ISSUE TITLE
Issue about 'NoneType'

### ISSUE THREAD

**Issue by LiQianRanOvO** [qq995431104/Copy-Paste-for-Semantic-Segmentation#4]
when run this copy_paste.py, it shows that:
Traceback (most recent call last):
  File "copy_paste.py", line 159, in <module>
    main(args)
  File "copy_paste.py", line 139, in main
    mask, img = copy_paste(mask_src, img_src, mask_main, img_main)
  File "copy_paste.py", line 98, in copy_paste
    mask_src, img_src = random_flip_horizontal(mask_src, img_src)
  File "copy_paste.py", line 23, in random_flip_horizontal
    img = img[:, ::-1, :]
TypeError: 'NoneType' object is not subscriptable

**Comment by xuanzhiliu** [comment]
I faced same error with you,do you solve it now?

**Comment by LiQianRanOvO** [comment]
Can you describe your error???




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月1日(星期一) 上午10:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qq995431104/Copy-Paste-for-Semantic-Segmentation] Issue about &#39;NoneType&#39; (Issue #4)





 
I faced same error with you,do you solve it now?

**Comment by xuanzhiliu** [comment]
> 

Thanks for your reply,I faced the error as same as yours,but I have solved it now!
I convert the JPEGImages from .png to .jpg and the error disappeared

**Comment by LiQianRanOvO** [comment]
It hear nice, good luck for you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月2日(星期二) 下午3:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qq995431104/Copy-Paste-for-Semantic-Segmentation] Issue about &#39;NoneType&#39; (Issue #4)





   
Thanks for your reply,I faced the error as same as yours,but I have solved it now!
 I convert the JPEGImages from .png to .jpg and the error disappeared
